messages:
  changed: "&6Changed gamemode to&c %gamemode%"
  no-permission: "&cNo permission to switch gamemode to &4%gamemode%"
  usage: "&cUsage: /gamemode <gamemode>"
  unknown: "&cUnknown gamemode: &4%gamemode%"
  console: "&cThis command cannot be used from the console"